name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Chris Naude
main: com.cnaude.dynwarp.DynWarp
depends: dynmap
commands:
    dwlist:
        description: List Dynmap marker warps.
        usage: /<command>
        aliases: [ dwl ]
    dwarp:
        description: Warp to a Dynmap marker.
        usage: /<command> [marker/label]
        aliases: [ dw ]
permissions: 
    dynwarp.tp:
        description: Gives player access to /dwarp and /dw.
        default: op 
    dynwarp.list:
        description: Gives player access to /dwlist and /dwl.
        default: op 
